# Name and version of the dbt project 
name: rag_test
version: 1.0.0

# Profile to use for database connections
profile: default

# Configuration version for the dbt project
config-version: 2

# Paths for project components
model-paths: ["models"]        # Model files
macro-paths: ["macros"]        # Macros (reusable code)
seed-paths: ["data"]           # Seed CSV files
test-paths: ["tests"]          # Test files
analysis-paths: ["analysis"]   # Analysis SQL files

# Target directory for compiled files and clean-up targets
target-path: "target"
clean-targets: ["target"]

# Configuration for seed models
seeds:
  rag_test:
    +schema: raw  # Changed schema name for seeds
    +alias: processed_data  # Optional: Control the table name if needed

# Configuration for models
models:
  rag_test:
    +schema: main
    staging:
      +schema: staging
    marts:
      +schema: marts

# Add these configurations:
vars:
  # Define common variables here
  schema_prefix: "{{ env_var('DBT_SCHEMA') }}"
  
# Add documentation configuration
docs-paths: ["docs"]
asset-paths: ["assets"]

# Add test severity levels
tests:
  +severity: warn  # or error
