version: 2

models:
  - name: embeddings
    description: "Table storing document content and their vector embeddings"
    columns:
      - name: id
        description: "Unique identifier for each embedding"
        tests:
          - unique
          - not_null
      - name: content
        description: "The text content that was embedded"
        tests:
          - not_null
      - name: embedding
        description: "Vector embedding of the content"
        tests:
          - not_null
      - name: document_hash
        description: "Hash of the document content"
        tests:
          - not_null
      - name: created_at
        description: "Timestamp when the embedding was created"
        tests:
          - not_null
      - name: loaded_at_field
        description: "Timestamp when the embedding was loaded"
        tests:
          - not_null
      - name: freshness
        description: "Freshness of the embedding"
        tests:
          - not_null

sources:
  - name: raw
    schema: raw
    tables:
      - name: embeddings

freshness:
  - name: embeddings
    loaded_at_field: created_at
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}